name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Prepare stage-4 tempdir
      run: |
        cd ./stage-4
        rm -rf ./tempdir
        mkdir -p ./tempdir/templates
        mkdir -p ./tempdir/static
        mkdir -p ./tempdir/scheduler
        mkdir -p ./tempdir/worker

        cp ./app.py ./tempdir/ 2>/dev/null || true
        cp ./requirements.txt ./tempdir/ 2>/dev/null || true
        cp ./requirements.txt ./tempdir/scheduler/ 2>/dev/null || true
        cp ./scheduler/*.py ./tempdir/scheduler/ 2>/dev/null || true
        cp ./worker/*.py ./tempdir/worker/ 2>/dev/null || true
        cp -r ./templates/* ./tempdir/templates/ 2>/dev/null || true
        cp -r ./static/* ./tempdir/static/ 2>/dev/null || true

        cat << 'EOF' > ./tempdir/Dockerfile
        FROM python
        WORKDIR /home/myapp
        COPY ./requirements.txt .
        COPY ./static ./static
        COPY ./templates ./templates
        COPY ./app.py .
        RUN sed -i '/apturl/d' requirements.txt && \
            pip install --no-cache-dir -r requirements.txt
        EXPOSE 8080
        CMD ["python3", "app.py"]
        EOF

        cat << 'EOF' > ./tempdir/scheduler/Dockerfile
        FROM python
        WORKDIR /home/scheduler
        COPY ./requirements.txt .
        COPY ./*.py .
        RUN sed -i '/apturl/d' requirements.txt && \
            pip install --no-cache-dir -r requirements.txt
        EXPOSE 2973
        CMD ["python3", "scheduler.py"]
        EOF

        cat << 'EOF' > ./tempdir/worker/Dockerfile
        FROM python
        WORKDIR /home/worker
        COPY ./*.py .
        RUN pip install --no-cache-dir pika pymongo "paramiko<4" netmiko ntc-templates
        CMD ["python3", "consumer.py"]
        EOF

        cat << 'EOF' > ./tempdir/docker-compose.yml
        services:
          web:
            build: .
            ports:
              - "8080:8080"
            depends_on:
              - mongo
            networks:
              - app-net
            env_file:
              - .env
            environment:
              MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
              DB_NAME: "${DB_NAME}"

          mongo:
            image: mongo:6
            ports:
              - "27017:27017"
            volumes:
              - mongo-data:/data/db
            networks:
              - app-net
            env_file:
              - .env

          rabbitmq:
            image: rabbitmq:3-management
            ports:
              - "5672:5672" # AMQP Protocol port
              - "15672:15672" # Web Management UI
            networks:
              - app-net
            env_file:
              - .env
            environment:
              RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
              RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            volumes:
              - rabbitmq_data:/data/rabbitmq

          scheduler:
            build: ./scheduler/
            ports:
              - 2973:2973
            networks:
              - app-net
            depends_on:
              - mongo
              - rabbitmq
            env_file:
              - .env
            environment:
              MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
              DB_NAME: "${DB_NAME}"
              COLLECTIONS_NAME: "${COLLECTIONS_NAME}"
              RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
              RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
              RABBITMQ_ROUTER_QUEUE_JOBS: ${RABBITMQ_ROUTER_QUEUE_JOBS}
              RABBITMQ_ROUTER_EXCHANGE: ${RABBITMQ_ROUTER_EXCHANGE}
              RABBITMQ_ROUTER_ROUTING_KEY: ${RABBITMQ_ROUTER_ROUTING_KEY}
              PRODUCER_HOST: ${PRODUCER_HOST}

          worker:
            build: ./worker/
            networks:
              - app-net
            depends_on:
              - rabbitmq
              - mongo
            env_file:
              - .env
            environment:
              MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
              DB_NAME: "${DB_NAME}"
              RABBITMQ_HOST: ${PRODUCER_HOST}
              RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
              RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}


        volumes:
          mongo-data:
          rabbitmq_data:

        networks:
          app-net:
        EOF

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.3

    - name: Install Lint & Format Tools
      run: |
        pip install flake8 black

    - name: Run flake8 (Lint)
      run: flake8 ./stage-4/tempdir

    - name: Check code format with black
      run: black --check ./stage-4/tempdir

    - name: Check Docker Versions
      run: |
        docker --version
        docker compose version

    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Docker Images
      if: github.event_name == 'push'
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest ./stage-4/tempdir/worker
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/scheduler:latest ./stage-4/tempdir/scheduler
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/web:latest ./stage-4/tempdir

        docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/scheduler:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/web:latest
